### ISSUE TITLE
MELPA package

### ISSUE THREAD

**Issue by vzaliva** [ProofGeneral/opam-switch-mode#5]
Feature request: It would be great if this package is available via MELPA so we can install it via `use-package`.

**Comment by erikmd** [comment]
Thanks @vzaliva for your input!

Submitting this package on MELPA was already on the roadmap 🙂, I was assigned to do so at the last PG-maint-telco with @hendriktews and @Matafou, but couldn't do it sooner while on vacation.

**Comment by erikmd** [comment]
@vzaliva:

* see PR https://github.com/melpa/melpa/pull/8167

**Comment by Matafou** [comment]
Thanks for the work Erik.

**Comment by vzaliva** [comment]
Thanks, Erik. Please note that MELPA PR is not merged due to some warnings.

**Comment by erikmd** [comment]
Yes, thanks @vzaliva; I'll try to address the review soon.

**Comment by erikmd** [comment]
FYI @vzaliva @ProofGeneral/core:

* PR https://github.com/melpa/melpa/pull/8167 was just merged;
* so <kbd>M-x package-install opam-switch-mode RET</kbd> can now be used.

I propose we close this issue #5 only when the installation procedure of opam-switch-mode is updated (at least in README.md)
