### ISSUE TITLE
tureg+merlin support

### ISSUE THREAD

**Issue by vzaliva** [ProofGeneral/opam-switch-mode#9]
I tried to use it with Merlin+tuareg, but it fails to find `ocamlmerlin` binary which was not installed in the original switch but is in the switch I have switched to.

**Comment by erikmd** [comment]
Hi @vzaliva !, thanks for your input.

There is no theoretical impediment indeed, to being able to use opam-switch-mode with tuareg+merlin. Just possible compatibility bugs :)

@monnier told me a few days ago that he was interested in taking a look at this point to ensure this compatibility (then, we could remove/replace the tuareg function `M-x tuareg-opam-update-env` that is subsumed by opam-switch-mode)

*see also https://coq.zulipchat.com/#narrow/stream/237977-Coq-users/topic/ProofGeneral.20release.204.2E5/near/309621450*

so, I propose to assign @monnier to this issue :)

**Comment by erikmd** [comment]
* See also https://github.com/ocaml/merlin/issues/1591

**Comment by erikmd** [comment]
**FYI:** tuareg+merlin support has just been submitted upstream!

* https://github.com/ocaml/tuareg/pull/307
* https://github.com/ocaml/merlin/pull/1654

And opam-switch-mode itself is now available in:

* [MELPA](https://melpa.org/#/opam-switch-mode)
* [MELPA Stable](https://stable.melpa.org/#/opam-switch-mode)
* [NonGNU-devel](https://elpa.nongnu.org/nongnu-devel/opam-switch-mode.html)
* [NonGNU](https://elpa.nongnu.org/nongnu/opam-switch-mode.html)

Cc @vzaliva @YaZko @ProofGeneral/core @hendriktews @Matafou @monnier @cpitclaudel

**Comment by erikmd** [comment]
Dear all,
Closing this issue as opam-switch-mode support now goes live in tuareg+merlin!
